version: '3'
services:
  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 3306
      MB_DB_USER: youruser
      MB_DB_PASS: yourpassword
      MB_DB_HOST: yourhost

